# Generated by Django 5.0 on 2023-12-06 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_search', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MagnetLinks',
            new_name='MagnetLink',
        ),
    ]
